//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisNo { get; set; }
        public Nullable<int> TC { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> SatisFiyati { get; set; }
        public Nullable<int> ToplamFiyat { get; set; }
        public Nullable<int> BarkodNo { get; set; }
    
        public virtual Urunler Urunlers { get; set; }
    }
}
