//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Satislars = new HashSet<Satislar>();
        }
    
        public int BarkodNo { get; set; }
        public string Kategori { get; set; }
        public string Marka { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> AlisFiyati { get; set; }
        public Nullable<int> SatisFiyati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislars { get; set; }
    }
}
